apiVersion: v1
kind: Service
metadata:
  name: kube-dns-metrics
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  ports:
  - name: metrics
    port: 9153
    targetPort: metrics
  selector:
    k8s-app: kube-dns